In [1]:
from configparser import ConfigParser
import subprocess

In [2]:
root_dir = '/teamspace/studios/this_studio/mouse-sleep-analysis/configuration_files/'
expFile = 'exp_details'
inputConfiguration = 'input_configuration'

In [3]:
config = ConfigParser()
config.read(f'{root_dir}{expFile}')

exp_ID = config.get('EXP_DETAILS', 'expID')
exps_dir = config.get('EXP_DETAILS', 'expsDir')
dset_dir = config.get('EXP_DETAILS', 'dsetDir')
states_file = config.get('EXP_DETAILS', 'statesFile')

config.read(f'{root_dir}{inputConfiguration}')
num_fac = config.get('MODEL_PARAMETER_SETTING', 'num_fac')
num_hid_cov = config.get('MODEL_PARAMETER_SETTING', 'num_hid_cov')
num_hid_mean = config.get('MODEL_PARAMETER_SETTING', 'num_hid_mean')

model_name = f'ws_fac{num_fac}_cov{num_hid_cov}_mean{num_hid_mean}'

In [4]:
base_dir = f"{exps_dir}{exp_ID}/"

In [5]:
command = f"python3 /teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py -f {base_dir} -done True -input {dset_dir} -md {base_dir} -m {model_name} -s {states_file}"
subprocess.run(command, shell=True)

Initialization...
args.f : /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD_OS_Basic_RGS14_Control_W35_N40_R25_total_144000/
args.done : True
args.md /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD_OS_Basic_RGS14_Control_W35_N40_R25_total_144000/
args.input /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/input/
args.m : ws_fac11_cov11_mean10
args.s : TD_OS_Basic_RGS14_Control_W35_N40_R25_total_144000_manual_scoring.mat
finalModel: ws_fac11_cov11_mean10
Loading data...
Analysing experiment :  /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD_OS_Basic_RGS14_Control_W35_N40_R25_total_144000
Computing latent states...
/teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD_OS_Basic_RGS14_Control_W35_N40_R25_total_144000/ws_fac11_cov11_mean10
logisticArg_c min :  2.7374778
logisticArg_c max :  5.0473332
logisticArg_c mean :  3.7293594
True
logisticArg_m min :  -67

/teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py:47: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  if not os.path.isdir('epoch%d' % self.epochID):
/teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py:48: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  os.makedirs('epoch%d' % self.epochID)
/teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py:50: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  os.ch

Computing the unique binary latent states...
The number of the unique latent activations is : 138
np.shape(uniqueAct) :  (138, 21)
np.unique(uniqueAct) : [0 1]
uniqueAct [[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
Checking if there are hidden_units that are always off..
The sum of the unique latent activations' columns is :  [138 138 138 138 138 138 138 138 138 138 138  40 117 105  88  30  46  60
  75  36  68]


CompletedProcess(args='python3 /teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py -f /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD_OS_Basic_RGS14_Control_W35_N40_R25_total_144000/ -done True -input /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/input/ -md /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD_OS_Basic_RGS14_Control_W35_N40_R25_total_144000/ -m ws_fac11_cov11_mean10 -s TD_OS_Basic_RGS14_Control_W35_N40_R25_total_144000_manual_scoring.mat', returncode=0)