In [18]:
import os
os.chdir('/teamspace/studios/this_studio/mouse-sleep-analysis/scripts')

import argparse
from testDataset import testDataset
from configparser import ConfigParser
import subprocess

In [19]:
root_dir = '/teamspace/studios/this_studio/mouse-sleep-analysis/configuration_files'
expFile = 'exp_details_test'
modelFile = 'input_configuration'

In [21]:
new_dataset = testDataset(root_dir, expFile)

new_dataset.loadData()

new_dataset.prepareFile()

base_dir = f"/teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/{new_dataset.expName}/"
model_dir = f"/teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/{new_dataset.modelDirName}/"
data_dir = new_dataset.dataDir
model_name = new_dataset.modelName
states_file = new_dataset.statesFile

command = f"python3 /teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py -f {base_dir} -done True -input {data_dir} -md {model_dir} -m {model_name} -s {states_file}"
subprocess.run(command, shell=True)

('initial size: ', (5135, 10))
Scaling...


Initialization...
args.f : /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/test1/
args.done : True
args.md /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD1_OS_RGS_untreated_W35_N40_R25_total_520000/
args.input /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/input/
args.m : ws_fac11_cov11_mean10
args.s : states.mat
finalModel: ws_fac11_cov11_mean10
Loading data...
Analysing experiment :  /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/test1
Computing latent states...
/teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD1_OS_RGS_untreated_W35_N40_R25_total_520000/ws_fac11_cov11_mean10
logisticArg_c min :  1.9707234
logisticArg_c max :  8.742189
logisticArg_c mean :  4.3571935
True
logisticArg_m min :  -47.443226
logisticArg_m max :  57.33999
logisticArg_m mean :  0.74308896
True
Storing in... /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experi

/teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py:47: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  if not os.path.isdir('epoch%d' % self.epochID):
/teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py:48: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  os.makedirs('epoch%d' % self.epochID)
/teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py:50: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  os.ch

Computing the unique binary latent states...
The number of the unique latent activations is : 53
np.shape(uniqueAct) :  (53, 21)
np.unique(uniqueAct) : [0 1]
uniqueAct [[1 1 1 ... 1 0 0]
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 1 0 0]
 ...
 [1 1 1 ... 0 0 1]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 1]]
Checking if there are hidden_units that are always off..
The sum of the unique latent activations' columns is :  [53 53 53 53 53 53 53 53 53 53 53 37 36 18 47 44 21 32 19  4 17]


CompletedProcess(args='python3 /teamspace/studios/this_studio/mouse-sleep-analysis/scripts/infer_states.py -f /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/test1/ -done True -input /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/input/ -md /teamspace/studios/this_studio/mouse-sleep-analysis/sample_data/experiments/TD1_OS_RGS_untreated_W35_N40_R25_total_520000/ -m ws_fac11_cov11_mean10 -s states.mat', returncode=0)